── 1. Failure:  (@test-expect-error.R#43)  ─────────────────────────────────────
`null()` did not throw an error.

── 2. Failure:  (@test-expect-error.R#44)  ─────────────────────────────────────
`stop("!")` threw an error.
Message: !
Class:   simpleError/error/condition

── 3. Failure:  (@test-expect-error.R#46)  ─────────────────────────────────────
`stop("xxx")` threw an error with unexpected message.
Expected match: "zzz"
Actual message: "xxx"

── 4. Failure:  (@test-expect-error.R#47)  ─────────────────────────────────────
`stop("xxx")` threw an error with unexpected class.
Expected class: zzz
Actual class:   simpleError/error/condition

── 5. Failure:  (@test-expect-error.R#48)  ─────────────────────────────────────
`stop("xxx")` threw an error with unexpected class and message.
Expected class: zzz
Actual class:   simpleError/error/condition
Expected match: "zzz"
Actual message: "xxx"

